version: "3.8" # ✅ Docker Compose에서 지원되는 버전 사용

services:
  python:
    build: .
    container_name: python_server
    volumes:
      - ./:/app # ✅ 로컬 디렉토리 마운트
    working_dir: /app
    command: ["python3", "-m", "http.server", "8000"] # ✅ Python 서버 실행
    ports:
      - "8000:8000" # ✅ 컨테이너 내부 8000번 포트를 외부에 노출
    restart: always # ✅ 컨테이너가 중단되면 자동 재시작
